vedantmgoyal2009/winget-pkgs-automation

packages/m/microsoft.bicep.json

https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/3803110088?check_suite_focus=true#step:3:579

Fix bicep repo

---

packages/c/caret.caret.json

https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/3803110088?check_suite_focus=true#step:3:145

Fix Repo for Caret & Skip

---

packages/l/luanroger.workoffice.json

https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/3803110088?check_suite_focus=true#step:3:522

Fix repo and release status

---

scripts/YamlCreate.ps1

From - https://github.com/microsoft/winget-pkgs/pull/33958

[YamlCreate] Add switch to override PR Check Setting

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
packages/j/johannesmillan.superproductivity.json
scripts/Automation.ps1

Merge changes from development branch

---

package_scripts/b/badlion.badlionclient.ps1
packages/b/badlion.badlionclient.json

Add Package: Badlion.BadlionClient

---

package_scripts/j/jellyfin.jellyfinserver.ps1
packages/j/jellyfin.jellyfinserver.json

Adding Jellyfin.JellyfinServer, fix #180.

add jellyfin.jellyfinserver

---

package_scripts/m/microsoft.onedrive.enterprise.ps1
package_scripts/m/microsoft.onedrive.insiders.ps1
package_scripts/m/microsoft.onedrive.internal.fast.ps1
package_scripts/m/microsoft.onedrive.internal.slow.ps1
package_scripts/m/microsoft.onedrive.ps1
packages/m/microsoft.onedrive.enterprise.json
packages/m/microsoft.onedrive.insiders.json
packages/m/microsoft.onedrive.internal.fast.json
packages/m/microsoft.onedrive.internal.slow.json
packages/m/microsoft.onedrive.json

Add Microsoft.OneDrive.*

---

package_scripts/m/microsoft.teams.continuousdeployment.ps1
packages/m/microsoft.teams.continuousdeployment.json

Add Microsoft.Teams.ContinuousDeployment

---

.github/labeler.yml
.github/workflows/pre-validation.yml
CONTRIBUTING.md
scripts/Automation.ps1

Minor improvements

---

.all-contributorsrc
.github/pull_request_template.md
README.md
scripts/YamlCreate.ps1

Bug fixes and improvements

---

packages/e/eugeny.terminus.json

Skip Eugeny.Terminus

---

packages/i/insomnia.insomniadesigner.json

Skip Insomnia.InsomniaDesigner

---

packages/w/wez.wezterm.json

Add Wezterm

---

packages/v/valinet.explorerpatcher.prerelease.json

Feat: Add valinet.ExplorerPatcher.Prerelease

---

packages/b/beekeeper-studio.beekeeper-studio.json

https://github.com/microsoft/winget-pkgs/pull/39858

Fix: Asset regex for beekeeper-studio

---

scripts/CheckUpdate.ps1

Add Helper Script

---

package_scripts/b/bravesoftware.bravebrowser.dev.ps1

Update bravesoftware.bravebrowser.dev version

---

package_scripts/b/bravesoftware.bravebrowser.nightly.ps1

Update BraveSoftware.BraveBrowser.Nightly to v98.x

---

package_scripts/b/bravesoftware.bravebrowser.beta.ps1

* https://github.com/microsoft/winget-pkgs/pull/43735

Chore: Update BraveSoftware.BraveBrowser.Beta to v98.x

---

scripts/YamlCreate.ps1

I believe this is the correct way to update? 🤔

chore: update YamlCreate.ps1 to v2.0.6

---

package_scripts/b/bravesoftware.bravebrowser.ps1

* https://github.com/microsoft/winget-pkgs/pull/43769

chore: update BraveSoftware.BraveBrowser to v98.x

---

packages/p/prometheus.wmiexporter.json

* https://github.com/microsoft/winget-pkgs/pull/44069

fix: Prometheus.WMIExporter regex

---

packages/m/msys2.msys2.json

* https://github.com/microsoft/winget-pkgs/pull/43819
I believe this will fix 1 of 2 issues?
I have no idea how to fix the PackageVersion string

fix: msys2.msys2 regex
